replicaCount: 1
image:
  repository: 572468360775.dkr.ecr.us-east-1.amazonaws.com/backend
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
ingress:
  host: backend.cloudcomputing.com

