replicaCount: 1
image:
  repository: 572468360775.dkr.ecr.us-east-1.amazonaws.com/frontend
  tag: latest
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
ingress:
  host: frontend.cloudcomputing.com

