replicaCount: 1
image:
  repository: 906269103174.dkr.ecr.us-east-1.amazonaws.com/frontend
  tag: latest
  pullPolicy: Always
service:
  type: NodePort
  port: 80
ingress:
  host: frontend.cloudcomputing.com

