apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
  type: {{ .Values.service.type }}

